# Generated by Django 5.1.7 on 2025-04-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='text',
            field=models.TextField(blank=True, default='Zadejte text odstavce'),
        ),
    ]
