# Generated by Django 5.1.7 on 2025-03-24 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('CSV', 'CSV File'), ('JSON', 'JSON File'), ('EXCEL', 'Excel File'), ('API', 'API Endpoint')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='data_sources/')),
                ('api_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='data_sources.datasource')),
            ],
        ),
    ]
